# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet to Get
email: akashkupatro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is all about related articles from various sources in the domain of 
  programming Languages, software design, server architectures, cryptography and
  tools that I came across and find useful.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aptro.github.io" # the base hostname & protocol for your site
twitter_username: akashkupatro
github_username:  aptro
linkedin_username: aptro

# Build settings
markdown: kramdown
